### ISSUE TITLE
Does it make sense for the Placeholder property of IPlaceholder to be read-only?

### ISSUE THREAD

**Issue by nacompllo** [dotnet/Microsoft.Maui.Graphics.Controls#113]
I'm fixing a bug in the Editor control in Android where the PlaceHolder doesn't disappear when text is typed in the Editor, but I've run into a bug where the Placeholder property of IPlaceholder is readonly which I don't think makes much sense.

<img width="711" alt="test04" src="https://user-images.githubusercontent.com/20904914/170742091-3a4dd332-f887-42e6-b623-4d88fc82efdc.png">

Here you can see the code that I have developed to remove the PlaceHolder when the Editor has text but the property is readonly, is there any other way to do this? or am I missing something?

<img width="563" alt="test05" src="https://user-images.githubusercontent.com/20904914/170742101-b85e767d-1150-4f41-b593-e6b52304b2a6.png">

**Comment by jsuarezruiz** [comment]
We would need a change in .NET MAUI first. Could you open an issue in the MAUI repository?

**Comment by nacompllo** [comment]
> We would need a change in .NET MAUI first. Could you open an issue in the MAUI repository?

Of course, I've already opened it!
https://github.com/dotnet/maui/issues/7662

**Comment by hartez** [comment]
It doesn't make sense to modify the placeholder text on the cross-platform IPlaceholder when updating the platform control's text. If you do that, then later if the platform control's text is cleared, the placeholder value will be empty on the platform control. 

You probably just need to call `DrawPlaceholder` on the `IEditorDrawable` again to clear out the placeholder text now that the editor has user text in it.
