### ISSUE TITLE
Possible to use cupertino datetime picker on Android?

### ISSUE THREAD

**Issue by stilren** [dotnet/Microsoft.Maui.Graphics.Controls#115]
When I try to force use of Cupertino controls the timepickers do not change. I am guessing this is because its native controls being used. Is this correct or is there a way to use Cupertino timepicker?

**Comment by jsuarezruiz** [comment]
You can use Cupertino to affect the UI of all the controls. However, there are some "mixed controls". I mean drawn controls but with a native part. DatePicker and TimePicker for now are using the native dialogs to pick a date or time.

![drawn-timepicker-cupertino](https://user-images.githubusercontent.com/6755973/177802930-7e28a7e1-cd04-4cf4-b67e-cd8b0cbc52a3.gif)
