### ISSUE TITLE
is this proto-type deprecated ?

### ISSUE THREAD

**Issue by hintsofttech** [dotnet/Microsoft.Maui.Graphics.Controls#120]
no updates or progress for this project found for a long time.
is this proto-type deprecated ?

**Comment by progmars** [comment]
Duplicate of #108

**Comment by jsuarezruiz** [comment]
And for now, only can share the same answer than https://github.com/dotnet/Microsoft.Maui.Graphics.Controls/issues/108#issuecomment-1083109110

Thanks for the interest in the project!
