### ISSUE TITLE
Community Help

### ISSUE THREAD

**Issue by saamerm** [dotnet/Microsoft.Maui.Graphics.Controls#30]
@jsuarezruiz 
I came here from today's community standup! 
@davidortinau mentioned that this repo could use some help from the community.
Should we create some issues for organization?

**Comment by jsuarezruiz** [comment]
Thanks for the interest!
After merging https://github.com/dotnet/Microsoft.Maui.Graphics.Controls/pull/29 I will create a status Wiki and associated issues so that anyone in the community could collaborate.

**Comment by Martinn2** [comment]
Any news here ?

**Comment by jsuarezruiz** [comment]
@Martinn2 Yes, already adding issues with specific tasks that anyone in the community can choose from.
