### ISSUE TITLE
"The project doesn't know how to run the profile GraphicsControls.Sample.WinUI"

### ISSUE THREAD

**Issue by ToolmakerSteve** [dotnet/Microsoft.Maui.Graphics.Controls#96]
Trying to build+run this on VS 2022, Version 17.1.0 Preview 1.1.

Build does not give errors - though it does give a warning at top of file (Visual Studio ran into an unexpected error ...) and generates a log file:

[VsProjectFault_Graphics_Controls_WinUI.failure.txt](https://github.com/dotnet/Microsoft.Maui.Graphics.Controls/files/7700237/VsProjectFault_Graphics_Controls_WinUI.failure.txt)

Run opens a message popup, as shown in title.

Opening Configuration Manager, the "deploy" checkbox for this project is disabled.

What could be preventing deployment?

**Comment by ToolmakerSteve** [comment]
Discovered that project's Dependencies have yellow warning triangle on:

* SDK
* * Microsoft.UniversalCRT.Debug
* * Microsoft.VCLibs
* * Microsoft.VCLibs.Desktop

Properties show these are Version=10.0.19041.0.

What are these referring to?  

Could this cause failure to deploy?

I do have 10.0.19041.0. Windows SDK installed.

**Comment by ToolmakerSteve** [comment]
Progress. Reinstalled some extensions:
* MSIX
* Windows App SDK C# (and C++) VS2022 template

Something I did got Visual Studio to realize there were missing items, this happened:

> Creating a new clean layout...
> Copying files: Total 115 mb to layout...
> Checking whether required frameworks are installed...
> Framework: Microsoft.ProjectReunion.0.8/X64, app package version 8005.278.2204.0 is not currently installed.
> Framework: Microsoft.VCLibs.140.00.Debug.UWPDesktop/X64, app package version 14.0.30035.0 is not currently installed.
> Installing missing frameworks...
> Registering the application to run from layout...
> Deployment complete (0:00:05.738). Full package name: "56dcbb67-4ab8-4d34-950e-1ba70ee4a762_1.0.0.0_neutral__9zz4h110yvjzm"
> ========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========

Now able to build.

HOWEVER: Those yellow triangle warnings on Dependencies / SDK / ... are still there.

When (F5) start Graphics.Controls.Sample.WInUI, get this exception:

>  System.ArgumentException
>   HResult=0x80070057
>   Message=Unable to create a wrapper object. The WinRT object 2248107425872 has type Microsoft.UI.Dispatching.DispatcherQueue which cannot be assigned to type Microsoft.UI.Dispatching.DispatcherQueue
>   Source=WinRT.Runtime
>   StackTrace:
>    at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
>    at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
>    at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
>    at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
>    at Microsoft.UI.Dispatching.DispatcherQueue.FromAbi(IntPtr thisPtr)
>    at ABI.Microsoft.UI.Dispatching.DispatcherQueue.FromAbi(IntPtr thisPtr)
>    at ABI.Microsoft.UI.Dispatching.IDispatcherQueueStatics.global::Microsoft.UI.Dispatching.IDispatcherQueueStatics.GetForCurrentThread()
>    at Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread()
>    at GraphicsControls.Sample.WinUI.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) in C:\2022repos\Microsoft.Maui.Graphics.Controls\src\GraphicsControls.Sample\GraphicsControls.Sample.WinUI\obj\Debug\net6.0-windows10.0.19041\win-x64\Platforms\Windows\App.g.i.cs:line 27
>    at ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(ApplicationInitializationCallback invoke)
>    at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
>    at ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr p)
>

**Comment by jsuarezruiz** [comment]
Have you installed https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17?
